name: Call Reusable Workflow to Push Artifact

on:
  push:
    branches:
      - main  # or the branch you want to trigger on

jobs:
  push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Secrets
        run: |
          echo "JFROG_URL: ${{ secrets.JFROG_URL }}"
          echo "JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}"
          echo "JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}"
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
