name: Call Reusable Workflow to Push Artifact

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow on

jobs:
  push-artifact:
    uses: Pratibhas54/SampleDotNetApp/.github/workflows/dotnet-build-and-push.yml@main
    with:
      dotnet_version: '8.0.x' 
      csproj_file: './TodoListApp.csproj'
      jfrog_artifact_path: 'test/Todolist'
  
